spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: pityke17
    password: "0402"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.pityke17.order.kafka.OrderConfirmation


server:
  port: 8070

application:
  config:
    ##connecting to api gateway(contains load balancer)
    ##(redirect the request to the microservice) for scaling
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments
