services:
  postgres:
    container_name: microservice_postgres ##pgadmin4 require the container name for the connection (hostname)
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pityke17
      POSTGRES_PASSWORD: "0402"
      POSTGRES_DB: "product_db"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
#        - ${PWD}/init.sql:/docker-entrypoint-initdb.d/V1__product_database.sql
    ports:
      - "5432:5432"
    networks:
      - microservice-net
    restart: always

  pgadmin:
    container_name: microservice_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:

      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservice-net
    restart: always

  mongodb:
    container_name: microservice_mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: pityke17
      MONGO_INITDB_ROOT_PASSWORD: 0402
    networks:
      - microservice-net
    restart: always

  mongo-express:
    container_name: microservice_mongo_express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - microservice-net

  mail-dev:
    container_name: microservice_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  microservice-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
